language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cloud119/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true cloud119/react-test npm test

after_success:
  - docker build -t cloud119/multi-client ./client
  - docker build -t cloud119/multi-nginx ./nginx
  - docker build -t cloud119/multi-server ./server
  - docker build -t cloud119/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cloud119/multi-client
  - docker push cloud119/multi-nginx
  - docker push cloud119/multi-server
  - docker push cloud119/multi-worker

# Login to the docker CLI
# Take those images and push them to docker hub..

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-397450896582
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY


